export { AboutPage } from './AboutPage'
export { CatalogPage } from './CatalogPage'
export { ContactsPage } from './ContactsPage'
export { ProfilePage } from './ProfilePage'
export { HomePage } from './HomePage'
export { NotFoundPage } from './NotFoundPage'
export { TestPage } from './TestPage'
